<?php

namespace Epic\R2RioBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * R2SearchResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class R2SearchResponseRepository extends EntityRepository
{
    public function update(R2SearchResponse $entity)
    {
        $this->_em->persist($entity);
        $this->_em->flush();
    }

    public function remove(R2SearchResponse $entity)
    {
        $this->_em->remove($entity);
        $this->_em->flush();
    }

    public function findOneByRequestCode($code)
    {
        $query = $this->createQueryBuilder('response');
        $query->innerJoin('response.searchRequest','request');
        $query->where($query->expr()->eq('request.code',':code'));
        $query->setParameter('code', $code);
        $query->setMaxResults(1);
        return $query->getQuery()->getOneOrNullResult();
    }
}
